spring:
  neo4j:
    uri: bolt://${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

org:
  neo4j:
    migrations:
      packages-to-scan:
        - io.picklegames.fungenerator.migrations