spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ngac_security_neo4j_pwd #secretpwd

org:
  neo4j:
    migrations:
      packages-to-scan:
        - io.picklegames.fungenerator.migrations